### ISSUE TITLE
Up/Down Toggles in Sizing Input Fields [Feature Request]

### ISSUE THREAD

**Issue by AlekSheff** [ProgenixLLC/product-uploader-beta#7]
**Describe the solution you'd like**
It would be nice to be able to arrow key up/down to adjust the size, position, width, etc., of images using the input fields.

Current: 
<img width="661" alt="image" src="https://github.com/ProgenixLLC/product-uploader-beta/assets/97270194/60a3ef5d-fd77-4a7f-a6e4-8862106cbc39">

Suggestion: 
<img width="1172" alt="image" src="https://github.com/ProgenixLLC/product-uploader-beta/assets/97270194/e7001c9e-0ca7-46e1-b9a8-b4504cf6f1c2">

**Comment by bigmac1337** [comment]
Released with v1.2.7-beta
